### ISSUE TITLE
[DataGrid] Rendered fewer hooks than expected when a column contains `Popover` elements.

### ISSUE THREAD

**Issue by mattcarlotta** [mui-org/material-ui-x#1376]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Rescaling the window when a `Popover` resides within a `DataGrid`  column will throw the following errors/warnings:

<details>
<summary>Click to expand error and warnings</summary>

```
react-dom.development.js:10062 Uncaught Error: Rendered fewer hooks than expected. This may be caused by an accidental early return statement.
    at renderWithHooks (react-dom.development.js:10062)
    at updateFunctionComponent (react-dom.development.js:11844)
    at updateSimpleMemoComponent (react-dom.development.js:11744)
    at beginWork (react-dom.development.js:13008)
    at HTMLUnknownElement.callCallback (react-dom.development.js:2746)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:2770)
    at invokeGuardedCallback (react-dom.development.js:2804)
    at beginWork$1 (react-dom.development.js:16114)
    at performUnitOfWork (react-dom.development.js:15339)
    at workLoopSync (react-dom.development.js:15293)
    at renderRootSync (react-dom.development.js:15268)
    at performSyncWorkOnRoot (react-dom.development.js:15008)
    at eval (react-dom.development.js:7457)
    at unstable_runWithPriority (scheduler.development.js:468)
    at runWithPriority$1 (react-dom.development.js:7417)
    at flushSyncCallbackQueueImpl (react-dom.development.js:7453)
    at flushSyncCallbackQueue (react-dom.development.js:7443)
    at scheduleUpdateOnFiber (react-dom.development.js:14776)
    at dispatchAction (react-dom.development.js:10817)
    at eval (index-esm.js:3716)
    at eval (index-esm.js:6702)
    at Ms.eval (index-esm.js:6713)
    at Ms.emit (index-esm.js:6416)
    at Object.eval [as publishEvent] (index-esm.js:6586)
    at Ms.e.current.hasOwnProperty.e.current.<computed> [as publishEvent] (index-esm.js:3437)
    at Object.eval [as resize] (index-esm.js:7342)
    at Ms.e.current.hasOwnProperty.e.current.<computed> [as resize] (index-esm.js:3437)
    at eval (index-esm.js:7374)
    at eval (index-esm.js:5167)
    at HTMLDivElement.eval (useEventCallback.js:14)
    at eval (index-esm.js:5122)
    at Array.forEach (<anonymous>)
    at eval (index-esm.js:5121)

The above error occurred in the <GridRowCells> component:
    at GridRowCells (https://1kcff.csb.app/node_modules/@material-ui/data-grid/dist/index-esm.js:3733:19)
    at div
    at GridRow (https://1kcff.csb.app/node_modules/@material-ui/data-grid/dist/index-esm.js:5285:24)
    at div
    at GridRenderingZone (https://1kcff.csb.app/node_modules/@material-ui/data-grid/dist/index-esm.js:5276:33)
    at div
    at GridStickyContainer (https://1kcff.csb.app/node_modules/@material-ui/data-grid/dist/index-esm.js:5311:22)
    at div
    at Xo (https://1kcff.csb.app/node_modules/@material-ui/data-grid/dist/index-esm.js:4134:21)
    at GridViewport (https://1kcff.csb.app/node_modules/@material-ui/data-grid/dist/index-esm.js:5321:15)
    at div
    at div
    at eval (https://1kcff.csb.app/node_modules/@material-ui/data-grid/dist/index-esm.js:4158:21)
    at div
    at eval (https://1kcff.csb.app/node_modules/@material-ui/data-grid/dist/index-esm.js:5158:20)
    at div
    at Ys (https://1kcff.csb.app/node_modules/@material-ui/data-grid/dist/index-esm.js:7216:8)
    at Xs (https://1kcff.csb.app/node_modules/@material-ui/data-grid/dist/index-esm.js:7192:1)
    at div
    at eval (https://1kcff.csb.app/node_modules/@material-ui/data-grid/dist/index-esm.js:4106:21)
    at NoSsr (https://1kcff.csb.app/node_modules/@material-ui/core/esm/NoSsr/NoSsr.js:12:24)
    at eval (https://1kcff.csb.app/node_modules/@material-ui/data-grid/dist/index-esm.js:7297:15)
    at eval (https://1kcff.csb.app/node_modules/@material-ui/data-grid/dist/index-esm.js:7501:13)
    at div
    at DataGridDemo

React will try to recreate this component tree from scratch using the error boundary you provided, Xs.

index.js:27 Warning: React does not recognize the `hasError` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `haserror` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at div
    at eval (https://1kcff.csb.app/node_modules/@material-ui/data-grid/dist/index-esm.js:4149:21)
    at eval (https://1kcff.csb.app/node_modules/@material-ui/data-grid/dist/index-esm.js:6515:19)
    at div
    at Ys (https://1kcff.csb.app/node_modules/@material-ui/data-grid/dist/index-esm.js:7216:8)
    at Xs (https://1kcff.csb.app/node_modules/@material-ui/data-grid/dist/index-esm.js:7192:1)
    at div
    at eval (https://1kcff.csb.app/node_modules/@material-ui/data-grid/dist/index-esm.js:4106:21)
    at NoSsr (https://1kcff.csb.app/node_modules/@material-ui/core/esm/NoSsr/NoSsr.js:12:24)
    at eval (https://1kcff.csb.app/node_modules/@material-ui/data-grid/dist/index-esm.js:7297:15)
    at eval (https://1kcff.csb.app/node_modules/@material-ui/data-grid/dist/index-esm.js:7501:13)
    at div
    at DataGridDemo

Material-UI: GridComponent - An unexpected error occurred. Error: Rendered fewer hooks than expected. This may be caused by an accidental early return statement..  Error: Rendered fewer hooks than expected. This may be caused by an accidental early return statement.
    at renderWithHooks (react-dom.development.js:10062)
    at updateFunctionComponent (react-dom.development.js:11844)
    at updateSimpleMemoComponent (react-dom.development.js:11744)
    at beginWork (react-dom.development.js:13008)
    at HTMLUnknownElement.callCallback (react-dom.development.js:2746)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:2770)
    at invokeGuardedCallback (react-dom.development.js:2804)
    at beginWork$1 (react-dom.development.js:16114)
    at performUnitOfWork (react-dom.development.js:15339)
    at workLoopSync (react-dom.development.js:15293)
    at renderRootSync (react-dom.development.js:15268)
    at performSyncWorkOnRoot (react-dom.development.js:15008)
    at eval (react-dom.development.js:7457)
    at unstable_runWithPriority (scheduler.development.js:468)
    at runWithPriority$1 (react-dom.development.js:7417)
    at flushSyncCallbackQueueImpl (react-dom.development.js:7453)
    at flushSyncCallbackQueue (react-dom.development.js:7443)
    at scheduleUpdateOnFiber (react-dom.development.js:14776)
    at dispatchAction (react-dom.development.js:10817)
    at eval (index-esm.js:3716)
    at eval (index-esm.js:6702)
    at Ms.eval (index-esm.js:6713)
    at Ms.emit (index-esm.js:6416)
    at Object.eval [as publishEvent] (index-esm.js:6586)
    at Ms.e.current.hasOwnProperty.e.current.<computed> [as publishEvent] (index-esm.js:3437)
    at Object.eval [as resize] (index-esm.js:7342)
    at Ms.e.current.hasOwnProperty.e.current.<computed> [as resize] (index-esm.js:3437)
    at eval (index-esm.js:7374)
    at eval (index-esm.js:5167)
    at HTMLDivElement.eval (useEventCallback.js:14)
    at eval (index-esm.js:5122)
    at Array.forEach (<anonymous>)
    at eval (index-esm.js:5121) undefined

Warning: React does not recognize the `errorInfo` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `errorinfo` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at div
    at eval (https://1kcff.csb.app/node_modules/@material-ui/data-grid/dist/index-esm.js:4149:21)
    at eval (https://1kcff.csb.app/node_modules/@material-ui/data-grid/dist/index-esm.js:6515:19)
    at div
    at Ys (https://1kcff.csb.app/node_modules/@material-ui/data-grid/dist/index-esm.js:7216:8)
    at Xs (https://1kcff.csb.app/node_modules/@material-ui/data-grid/dist/index-esm.js:7192:1)
    at div
    at eval (https://1kcff.csb.app/node_modules/@material-ui/data-grid/dist/index-esm.js:4106:21)
    at NoSsr (https://1kcff.csb.app/node_modules/@material-ui/core/esm/NoSsr/NoSsr.js:12:24)
    at eval (https://1kcff.csb.app/node_modules/@material-ui/data-grid/dist/index-esm.js:7297:15)
    at eval (https://1kcff.csb.app/node_modules/@material-ui/data-grid/dist/index-esm.js:7501:13)
    at div
    at DataGridDemo
```
</details>

## Expected Behavior 🤔

Not to throw errors/warnings.

## Steps to Reproduce 🕹

Reproduction Codesandbox:
[![Edit Data Grid Popover Bug](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/data-grid-popover-bug-1kcff?fontsize=14&hidenavigation=1&theme=dark)

Reproduction Demo: https://1kcff.csb.app/

Steps:

1. Open the demo link above.
2. Open the browser console and select the `Responsive Design Mode` button (firefox) or `Toggle device toolbar` button (chrome).
3. Quickly move the resize bars left/right and/or scale the window to about 500px, next exit out of responsive mode and then re-enter responsive mode.
4. Errors/Warnings will be thrown.

## Context 🔦

The idea behind using the popover is to provide condensed options to a single button that will only affect the row it resides in. This "actions" button would allow you to edit/delete/view/etc the record within the row (similar to this [AntDesign Table](https://ant.design/components/table/#components-table-demo-dynamic-settings)).

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
System:
    OS: Linux 5.8 Linux Mint 20.1 (Ulyssa)
  Binaries:
    Node: 14.16.0 - /usr/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 6.14.11 - /usr/bin/npm
  Browsers:
    Chrome: 89.0.4389.114
    Firefox: 87.0
  npmPackages:
    @emotion/react: ^11.1.5 => 11.1.5 
    @emotion/styled: ^11.1.5 => 11.1.5 
    @material-ui/core: ^4.11.3 => 4.11.3 
    @material-ui/data-grid: ^4.0.0-alpha.24 => 4.0.0-alpha.24 
    @material-ui/lab: ^4.0.0-alpha.57 => 4.0.0-alpha.57 
    @material-ui/pickers: ^3.3.10 => 3.3.10 
    @material-ui/styles:  4.11.3 
    @material-ui/system:  4.11.3 
    @material-ui/types:  5.1.0 
    @material-ui/utils:  4.11.2 
    @types/react:  16.9.49 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    typescript: ^4.2.3 => 4.2.3 
```
</details>

Chrome: https://youtu.be/GZU0YuMM0FM

Firefox: https://youtu.be/Mi7LwZD2Drk

**Comment by dtassone** [comment]
It is due to the way you use `renderCell`. You're passing a react component. Instead, you should be passing a function that returns a react node.
So if you replace your renderCell with `renderCell:  ()=> <ActionsButton />` it should work

**Comment by mattcarlotta** [comment]
> It is due to the way you use `renderCell`. You're passing a react component. Instead, you should be passing a function that returns a react node.
> So if you replace your renderCell with `renderCell: ()=> <ActionsButton />` it should work

Seems to be working as expected. Unfortunately, when passing `params` to the node, ESLint complains about the [component not having a displayName](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/display-name.md). I was able to work around this by using a traditional function expression instead of an anonymous arrow expression:
```tsx
{
  field: "actions",
  headerName: "Actions",
  renderCell: function Actions(params: GridValueGetterParams) {
     return (<TableActions params={params} />);
  }
}
```
If this unavoidable, I'll be happy to close this issue.

**Comment by dtassone** [comment]
have you tried with a lowercase name as renderCell is just a function not a react FC?
```tsx
{
  field: "actions",
  headerName: "Actions",
  renderCell: function actions(params: GridValueGetterParams) {
    return (<TableActions params={params} />);
  }
}
```

**Comment by mattcarlotta** [comment]
The problem is with using anonymous arrow functions within `renderCell` (as a workaround I can disable `react/display-name` and it still works -- though not sure if this approach impacts performance/optimizations):
```tsx
{
  field: "actions",
  headerName: "Actions",
  renderCell: (params: GridValueGetterParams) => <TableActions params={params} />
}
```

**Comment by oliviertassinari** [comment]
If I were to rank the different levels of solution on a scale, I would give the following points (its the relative value):

1. Helping @mattcarlotta fix his issue: 1. 
2. Having an issue with a clear title and a description that other developers can search from and find the answer: 20.
3. Having a clear description in the documentation that prevents developers to fall into this trap: 100.
4. Having a warning at runtime to give an instant feedback loop to the developers 500.

So far, we have done 1 a bit of 2. 4 is out of reach. @dtassone I would like to reopen this issue as we have barely solved it. This will very likely be a recurring theme.

Coming back to our previous conversation about creating multiple issues or having a single one, the drawback of creating multiple is that it fragments the context of the issue. You can no longer find a single place where the whole problem is focused. As for the metric of how many GitHub issues are closed or PRs are merged, I don't think that it matters in comparison to solving root causes. 

We could do 3 here with a simple change in the documentation:

```diff
diff --git a/docs/src/pages/components/data-grid/rendering/rendering.md b/docs/src/pages/components/data-grid/rendering/rendering.md
index 0ebaf4ef..629990ca 100644
--- a/docs/src/pages/components/data-grid/rendering/rendering.md
+++ b/docs/src/pages/components/data-grid/rendering/rendering.md
@@ -101,6 +101,12 @@ const columns: GridColDef[] = [

 {{"demo": "pages/components/data-grid/rendering/RenderCellGrid.js", "defaultCodeOpen": false, "bg": "inline"}}

+> ⚠️ The `renderCell` property expects a render function.
+> You can't provide a component directly.
+> If you do, you can expect errors like this `Rendered fewer hooks than expected` to throw.
+>
+> To use a component, do: `renderCell: () => <MyComponent />`.
+
 #### Expand cell renderer

 By default, the grid cuts the content of a cell and renders an ellipsis if the content of the cell does not fit in the ce
```

<img width="895" alt="Screenshot 2021-04-11 at 20 19 23" src="https://user-images.githubusercontent.com/3165635/114316300-3cab5280-9b03-11eb-82ce-01ddbfec05c2.png">

@mattcarlotta Would you like to make a PR for it? :)

**Comment by mattcarlotta** [comment]
@oliviertassinari 

Just to clarify how this issue propped up...

## Problem
Using anonymous function expressions within `renderCell` throws this ESLint warning:
![Screenshot from 2021-04-11 11-29-38](https://user-images.githubusercontent.com/22607722/114316690-70618a80-9ab9-11eb-8e1a-f396c757b6c7.png)

To mitigate the warning, I passed a component (shown below), which fixed the warning, but caused the render too many hooks issue mentioned above:

```tsx
const ExampleComponent = (params: GridValueGetterParams) => (
   <Component params={params} />
);

const Columns: GridColumns = [
  { field: "_id", headerName: "Database Id", flex: 1 },
  {
    field: "example",
    headerName: "Example",
    flex: 1,
    renderCell: ExampleComponent
  }
];
```
## Workaround

By either disabling the ESLint rule:
```
/* eslint-disable react/display-name */
```

Or by using a **named** traditional function:
```tsx
const Columns: GridColumns = [
  { field: "_id", headerName: "Database Id", flex: 1 },
  {
    field: "example",
    headerName: "Example",
    flex: 1,
    renderCell: function Example(params: GridValueGetterParams) { 
      return (
        <ExampleComponent params={params} />
      );
    }
  }
];
``` 

## Solutions

While including updated `renderCell` documentation might prevent the main issue from coming up, it doesn't address the ESLint warning. Perhaps the documentation can also include (or focus on) how to mitigate this [warning](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/display-name.md).

On that note, your option 4 could be implemented... 
[![Edit RenderCell Component Type Checking](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/rendercell-component-type-checking-m7r3h?fontsize=14&hidenavigation=1&theme=dark)
```

**Comment by oliviertassinari** [comment]
@mattcarlotta Interesting

1. Our repositories don't use this eslint rule, it's turned off [from the airbnb's config](https://github.com/airbnb/javascript/blob/730b74927432d5931f9047322e925fb7e1c07be6/packages/eslint-config-airbnb/rules/react.js#L51).
1. The eslint issue looks like a false-positive. It's already reported in https://github.com/yannickcr/eslint-plugin-react/issues/2751.
1. I don't see how https://codesandbox.io/s/rendercell-component-type-checking-m7r3h is correct. The main difference between a render function (supported) and a component (not supported) is either its uses hooks or not.

**Comment by mattcarlotta** [comment]
Admittedly, I haven't looked at the source, but the idea behind the codesandbox is to check if whatever is passed to `renderCell` is a **function** and it's **not named** before it's invoked. Regardless of whether or not it's using pure functions/hooks/classes, if I were to try to pass a component directly to `renderCell`, then it wouldn't pass the check because the function would be named. 

## Example

Let's say I want to render this component within a DataGrid cell:
**Example.tsx**:
```tsx
import * as React from "react";
import { Button, Popover } from "@material-ui/core";
import type { GridValueGetterParams } from "@material-ui/data-grid";

export const Example = (params: GridValueGetterParams): JSX.Element => {
  const [anchorEl, setAnchorEl] = React.useState<HTMLButtonElement | null>(
    null
  );

  const handleClick = (event: React.MouseEvent<HTMLButtonElement>): void => {
    setAnchorEl(event.currentTarget);
  };

  const handleClose = (): void => {
    setAnchorEl(null);
  };

  const open = Boolean(anchorEl);
  const id = open ? "user-settings" : undefined;

  return (
    <>
      <Button
        variant="contained" 
        color="primary"
        aria-describedby={id}
        onClick={handleClick}
      >
        <Avatar avatar={avatar} />
      </Button>
      <Popover
        id={id}
        open={open}
        anchorEl={anchorEl}
        onClose={handleClose}
        anchorOrigin={{
          vertical: "bottom",
          horizontal: "left"
        }}
        transformOrigin={{
          vertical: "top",
          horizontal: "center"
        }}
      >
        <div>
           params.getValue("_id")
        </div>
      </Popover>
    </>
  );
};

export default Example;
```

...and this component as well:
**ExampleTwo.tsx**:
```tsx
export default () => <div>Example Two</div>
```

## Result - Fail

I passed `renderCell` my components, but they would fail the checks because `renderCell` would contain a named functions: `renderCell: Example f()` and `renderCell: _default f()`:

**Columns.tsx**
```tsx
import type { GridColumns } from "@material-ui/data-grid";
import Example from "./Example";
import ExampleTwo from "./ExampleTwo";

const Columns: GridColumns = [
  { field: "_id", headerName: "Database Id", flex: 1 },
  {
    field: "example",
    headerName: "Example",
    flex: 1,
    renderCell: Example
  },
  {
    field: "exampletwo",
    headerName: "Example Two",
    flex: 1,
    renderCell: ExampleTwo
  }
];
```

This holds true for anonymous default imports/exports since webpack prefixes them with `_default`.

## Result - Pass

Alternatively, if I passed `renderCell` an **anonymous function** that returns my component, then it would pass the checks because `renderCell` must be an unnamed function: `renderCell: fn()`:

```tsx
import type { GridColumns, GridValueGetterParams } from "@material-ui/data-grid";
import Example from "./Example";
import ExampleTwo from "./ExampleTwo";

const Columns: GridColumns = [
  { field: "_id", headerName: "Database Id", flex: 1 },
  {
    field: "example",
    headerName: "Example",
    flex: 1,
    renderCell: (params: GridValueGetterParams) => <Example {...params} />
  },
  {
    field: "exampletwo",
    headerName: "Example Two",
    flex: 1,
    renderCell: () => <ExampleTwo />
  }
];
```

## Summation

The checks work by eliminating all possibilities except anonymous (unnamed) functions. The only way for the `renderCell` to be valid would be to use a render function:
```
() => ReactNode
```
or
```
function () {
  return ReactNode;
}
```

**Comment by oliviertassinari** [comment]
@mattcarlotta Thanks for the exploration. I don't think that it's enough. It would fail in our demos:

https://github.com/mui-org/material-ui-x/blob/4541efc4f9dfc49f2eed8d9b9956f7a2f6cb8be8/docs/src/pages/components/data-grid/rendering/RenderExpandCellGrid.tsx#L133

**Comment by oliviertassinari** [comment]
The discussion continues in #1402, I have, more or less copy & paste this issue description
