### ISSUE TITLE
[DataGrid] React does not recognize the `defaultProps` prop on a DOM element

### ISSUE THREAD

**Issue by jbty** [mui-org/material-ui-x#1993]
- [ x ] The issue is present in the latest release.
- [ x ] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Reproduction: https://codesandbox.io/s/material-demo-forked-xeimg?file=/demo.js

On dev server when i use the Datagrid component I get this red warning :

```
Warning: React does not recognize the `defaultProps` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `defaultprops` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

    at div
    at http://localhost:3000/static/js/vendors~main.chunk.js:1343:73
    at TablePagination (http://localhost:3000/static/js/vendors~main.chunk.js:41213:84)
    at http://localhost:3000/static/js/vendors~main.chunk.js:61000:11
    at div
    at http://localhost:3000/static/js/vendors~main.chunk.js:59109:13
    at http://localhost:3000/static/js/vendors~main.chunk.js:60935:11
    at div
    at Jc (http://localhost:3000/static/js/vendors~main.chunk.js:64737:11)
    at Zc (http://localhost:3000/static/js/vendors~main.chunk.js:64635:193)
    at Xc (http://localhost:3000/static/js/vendors~main.chunk.js:64673:13)
    at div
    at NoSsr (http://localhost:3000/static/js/vendors~main.chunk.js:27107:24)
    at http://localhost:3000/static/js/vendors~main.chunk.js:59020:11
    at Uc (http://localhost:3000/static/js/vendors~main.chunk.js:64613:18)
    at http://localhost:3000/static/js/vendors~main.chunk.js:65077:16
    at http://localhost:3000/static/js/vendors~main.chunk.js:65098:11
    at StyledComponent (http://localhost:3000/static/js/vendors~main.chunk.js:289635:28)
    at div
    at http://localhost:3000/static/js/vendors~main.chunk.js:1343:73
    at Paper (http://localhost:3000/static/js/vendors~main.chunk.js:28609:84)
    at FaDataTab (http://localhost:3000/static/js/3.chunk.js:264:22)
    at div
    at http://localhost:3000/static/js/vendors~main.chunk.js:1343:73
    at Grid (http://localhost:3000/static/js/vendors~main.chunk.js:18366:90)
    at div
    at http://localhost:3000/static/js/vendors~main.chunk.js:1343:73
    at Grid (http://localhost:3000/static/js/vendors~main.chunk.js:18366:90)
    at PartialWindTurbineList (http://localhost:3000/static/js/6.chunk.js:1071:27)
    at div
    at Transition (http://localhost:3000/static/js/vendors~main.chunk.js:352303:30)
    at CSSTransition (http://localhost:3000/static/js/vendors~main.chunk.js:351420:35)
    at div
    at TransitionGroup (http://localhost:3000/static/js/vendors~main.chunk.js:352872:30)
    at PageLayout (http://localhost:3000/static/js/1.chunk.js:428:20)
    at GlobalDataScreen (http://localhost:3000/static/js/6.chunk.js:452:84)
    at B (http://localhost:3000/static/js/vendors~main.chunk.js:350656:10)
    at Suspense
    at div
    at http://localhost:3000/static/js/vendors~main.chunk.js:1343:73
    at Container (http://localhost:3000/static/js/vendors~main.chunk.js:13361:84)
    at main
    at div
    at DefaultLayout (http://localhost:3000/static/js/main.chunk.js:6523:85)
    at InnerThemeProvider (http://localhost:3000/static/js/vendors~main.chunk.js:290090:72)
    at ThemeProvider (http://localhost:3000/static/js/vendors~main.chunk.js:287873:24)
    at ThemeProvider (http://localhost:3000/static/js/vendors~main.chunk.js:290109:24)
    at App (http://localhost:3000/static/js/main.chunk.js:82:93)
    at x (http://localhost:3000/static/js/vendors~main.chunk.js:350674:13)
    at w (http://localhost:3000/static/js/vendors~main.chunk.js:350295:13)
    at I18nextProvider (http://localhost:3000/static/js/vendors~main.chunk.js:346158:19)
    at div
    at PwaProvider (http://localhost:3000/static/js/main.chunk.js:7174:23)
    at Provider (http://localhost:3000/static/js/vendors~main.chunk.js:347566:20)
```

I strange because the error disappear on production build.

package.json:
```json
{
  "name": "ezefzef",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "develop": "react-scripts start",
    "serve": "serve -s build",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "husky:prepare": "husky install"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not op_mini all"
  ],
  "dependencies": {
    "@date-io/date-fns": "^2.10.11",
    "@emotion/react": "^11.4.0",
    "@emotion/styled": "^11.3.0",
    "@fontsource/inter": "^4.4.5",
    "@fontsource/roboto": "^4.4.5",
    "@lottiefiles/react-lottie-player": "^3.3.1",
    "@material-ui/core": "^5.0.0-alpha.38",
    "@material-ui/data-grid": "^4.0.0-alpha.32",
    "@material-ui/icons": "^5.0.0-alpha.37",
    "@material-ui/lab": "^5.0.0-alpha.38",
    "@material-ui/styled-engine-sc": "^5.0.0-alpha.11",
    "@material-ui/styles": "^5.0.0-alpha.36",
    "@reduxjs/toolkit": "^1.6.0",
    "@testing-library/jest-dom": "^5.14.1",
    "@testing-library/react": "^12.0.0",
    "@testing-library/user-event": "^13.1.9",
    "@types/jest": "^26.0.23",
    "@types/leaflet": "^1.7.3",
    "@types/material-ui": "^0.21.8",
    "@types/node": "^15.12.5",
    "@types/react": "^17.0.11",
    "@types/react-dom": "^17.0.8",
    "@types/react-helmet": "^6.1.1",
    "@types/react-redux": "^7.1.16",
    "@types/react-router-dom": "^5.1.7",
    "@typescript-eslint/eslint-plugin": "^4.28.1",
    "@typescript-eslint/parser": "^4.28.1",
    "animated-number-react": "^0.1.2",
    "axios": "^0.21.1",
    "clsx": "^1.1.1",
    "date-fns": "^2.22.1",
    "geolib": "^3.3.1",
    "history": "^5.0.0",
    "i18next": "^20.3.2",
    "i18next-browser-languagedetector": "^6.1.2",
    "i18next-http-backend": "^1.2.6",
    "leaflet": "^1.7.1",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-helmet": "^6.1.0",
    "react-i18next": "^11.11.0",
    "react-leaflet": "^3.2.0",
    "react-redux": "^7.2.4",
    "react-router-dom": "^6.0.0-beta.0",
    "react-scripts": "4.0.3",
    "react-transition-group": "^4.4.2",
    "styled-components": "^5.3.0",
    "stylelint-config-recommended": "^5.0.0",
    "stylelint-config-styled-components": "^0.1.1",
    "stylelint-processor-styled-components": "^1.10.0",
    "typescript": "^4.3.4",
    "web-vitals": "^2.0.1",
    "workbox-background-sync": "^6.1.5",
    "workbox-broadcast-update": "^6.1.5",
    "workbox-cacheable-response": "^6.1.5",
    "workbox-core": "^6.1.5",
    "workbox-expiration": "^6.1.5",
    "workbox-google-analytics": "^6.1.5",
    "workbox-navigation-preload": "^6.1.5",
    "workbox-precaching": "^6.1.5",
    "workbox-range-requests": "^6.1.5",
    "workbox-routing": "^6.1.5",
    "workbox-strategies": "^6.1.5",
    "workbox-streams": "^6.1.5"
  },
  "devDependencies": {
    "@commitlint/cli": "^12.1.4",
    "@commitlint/config-conventional": "^12.1.4",
    "eslint": "^7.29.0",
    "eslint-config-airbnb": "^18.2.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-import-resolver-typescript": "^2.4.0",
    "eslint-plugin-import": "^2.23.4",
    "eslint-plugin-jsx-a11y": "^6.4.1",
    "eslint-plugin-prettier": "^3.4.0",
    "eslint-plugin-react": "^7.24.0",
    "eslint-plugin-react-hooks": "^4.2.0",
    "husky": "^6.0.0",
    "prettier": "^2.3.2",
    "stylelint": "^13.13.1",
    "stylelint-config-standard": "^22.0.0",
    "typescript": "^4.3.4"
  }
}
```

DataTable component
```javascript
import {
  GridColDef,
  GridToolbarContainer,
  GridToolbarExport,
} from '@material-ui/data-grid'
import React from 'react'
import Paper from '@material-ui/core/Paper'
import { CloudDownload } from '@material-ui/icons'
import {
  AnomalyTableRow,
  DetectionsTableRow,
  ReportTableRow,
  WindTurbinesTableRow,
} from '../../../typings/typings'

const CustomToolbar: React.FC = () => (
  <GridToolbarContainer
    style={{ justifyContent: 'flex-end', marginTop: '5px' }}
  >
    {
      // @ts-ignore
      <GridToolbarExport size="medium" startIcon={<CloudDownload />} />
    }
  </GridToolbarContainer>
)

type FaDataTabProps = {
  columns: GridColDef[]
  rows: Array<
    WindTurbinesTableRow | AnomalyTableRow | DetectionsTableRow | ReportTableRow
  >
}

const StyledDataGrid = styled(DataGrid)(() => ({
  '&&': {
    '&.MuiDataGrid-root .MuiDataGrid-cell:focus': {
      outline: 'none',
    },
    '&.MuiDataGrid-root .MuiDataGrid-columnHeader:focus, .MuiDataGrid-root .MuiDataGrid-cell:focus':
      {
        outline: 'none',
      },
    border: 'none',
  },
}))

const FaDataTab: React.FC<FaDataTabProps> = ({ columns, rows }) => (
  <Paper
    elevation={0}
    sx={{
      width: '100%',
      paddingLeft: 4,
      paddingRight: 4,
      paddingBottom: 1,
    }}
  >
    <StyledDataGrid
      columns={columns}
      rows={rows}
      loading={rows.length === 0}
      rowHeight={40}
      density="standard"
      autoHeight
      pagination
      pageSize={15}
      components={{
        Toolbar: CustomToolbar,
      }}
    />
  </Paper>
)

export default FaDataTab
```

The issue persist, even if I remove the styled component

**Comment by oliviertassinari** [comment]
Please provide a **minimal** reproduction test case with the latest version. This would help a lot 👷 .
A live example would be perfect. [This **codesandbox.io** template](https://material-ui.com/r/issue-template) _may_ be a good starting point. Thank you!

**Comment by jbty** [comment]
@oliviertassinari after investigate i found the problem. I try to set dynamicly the localisation of Data table. But maybe I missing something. I notice is missing a translation key for Datatable:

```javascript
{
    "MuiDataGrid": {
        "defaultProps": {
            "localeText": {
                "MuiTablePagination": undefined <================== this output errors : Error: Missing translation for key MuiTablePagination.
                "noRowsLabel": "No rows",
                "noResultsOverlayLabel": "No results found.",
                "errorOverlayDefaultLabel": "An error occurred.",
                "toolbarDensity": "Density",
                "toolbarDensityLabel": "Density",
                "toolbarDensityCompact": "Compact",
                "toolbarDensityStandard": "Standard",
                "toolbarDensityComfortable": "Comfortable",
                "toolbarColumns": "Columns",
                "toolbarColumnsLabel": "Select columns",
                "toolbarFilters": "Filters",
                "toolbarFiltersLabel": "Show filters",
                "toolbarFiltersTooltipHide": "Hide filters",
                "toolbarFiltersTooltipShow": "Show filters",
                "toolbarExport": "Export",
                "toolbarExportLabel": "Export",
                "toolbarExportCSV": "Download as CSV",
                "columnsPanelTextFieldLabel": "Find column",
                "columnsPanelTextFieldPlaceholder": "Column title",
                "columnsPanelDragIconLabel": "Reorder column",
                "columnsPanelShowAllButton": "Show all",
                "columnsPanelHideAllButton": "Hide all",
                "filterPanelAddFilter": "Add filter",
                "filterPanelDeleteIconLabel": "Delete",
                "filterPanelOperators": "Operators",
                "filterPanelOperatorAnd": "And",
                "filterPanelOperatorOr": "Or",
                "filterPanelColumns": "Columns",
                "filterPanelInputLabel": "Value",
                "filterPanelInputPlaceholder": "Filter value",
                "filterOperatorContains": "contains",
                "filterOperatorEquals": "equals",
                "filterOperatorStartsWith": "starts with",
                "filterOperatorEndsWith": "ends with",
                "filterOperatorIs": "is",
                "filterOperatorNot": "is not",
                "filterOperatorAfter": "is after",
                "filterOperatorOnOrAfter": "is on or after",
                "filterOperatorBefore": "is before",
                "filterOperatorOnOrBefore": "is on or before",
                "filterValueAny": "any",
                "filterValueTrue": "true",
                "filterValueFalse": "false",
                "columnMenuLabel": "Menu",
                "columnMenuShowColumns": "Show columns",
                "columnMenuFilter": "Filter",
                "columnMenuHideColumn": "Hide",
                "columnMenuUnsort": "Unsort",
                "columnMenuSortAsc": "Sort by ASC",
                "columnMenuSortDesc": "Sort by DESC",
                "columnHeaderFiltersLabel": "Show filters",
                "columnHeaderSortIconLabel": "Sort",
                "footerTotalRows": "Total Rows:",
                "checkboxSelectionHeaderName": "Checkbox selection",
                "booleanCellTrueLabel": "true",
                "booleanCellFalseLabel": "false"
            }
        }
    }
}
````

```javascript
import {
  esES,
  deDE,
  frFR,
  enUS,
  GridColDef,
  GridPageChangeParams,
  GridToolbarContainer,
  GridToolbarExport,
  GridToolbar,
  Localization,
  LocalizationV5,
} from '@material-ui/data-grid'
import React, { useEffect, useState } from 'react'
import Paper from '@material-ui/core/Paper'
import { CloudDownload } from '@material-ui/icons'
import Box from '@material-ui/core/Box'
import { useTranslation } from 'react-i18next'
import { StyledDataGrid } from './styles'
import {
  AnomalyTableRow,
  DetectionsTableRow,
  ReportTableRow,
  WindTurbinesTableRow,
} from '../../../typings/typings'
import { LANGUAGES_MAPPING } from '../../../constants/infos'

const CustomToolbar: React.FC = () => (
  <GridToolbarContainer
    style={{ justifyContent: 'flex-end', marginTop: '5px' }}
  >
    <GridToolbar />
  </GridToolbarContainer>
)

type FaDataTabProps = {
  columns: GridColDef[]
  rows: Array<
    WindTurbinesTableRow | AnomalyTableRow | DetectionsTableRow | ReportTableRow
  >
}

const FaDataTab: React.FC<FaDataTabProps> = ({ columns, rows }) => {
  const { i18n } = useTranslation('COMMON')

  const [pageSize, setPageSize] = React.useState<number>(15)

  const [currentLocaleText, setCurrentLocalText] = useState<Localization>(enUS)

  useEffect(() => {
    switch (i18n.languages[0]) {
      case 'fr':
        setCurrentLocalText(frFR)
        break
      case 'en':
        setCurrentLocalText(enUS)
        break
      case 'es':
        setCurrentLocalText(esES)
        break
      case 'de':
        setCurrentLocalText(deDE)
        break
      default:
        setCurrentLocalText(enUS)
        break
    }
    console.log(enUS)
    console.log(currentLocaleText)
  }, [i18n])

  const handlePageSizeChange = (params: GridPageChangeParams): void => {
    setPageSize(params.pageSize)
  }

  return (
    <Paper
      elevation={0}
      sx={{
        width: '100%',
        paddingLeft: 4,
        paddingRight: 4,
        paddingBottom: 1,
      }}
    >
      <StyledDataGrid
        localeText={
          // @ts-ignore
          currentLocaleText.components.MuiDataGrid.defaultProps.localeText
        }
        columns={columns}
        disableColumnMenu
        rows={rows}
        loading={rows.length === 0}
        rowHeight={40}
        density="standard"
        autoHeight
        pagination
        pageSize={pageSize}
        onPageSizeChange={handlePageSizeChange}
        rowsPerPageOptions={[15, 25, 50, 100]}
        components={{
          Toolbar: CustomToolbar,
        }}
      />
    </Paper>
  )
}

export default FaDataTab
```

If I remove the translations system that I've created there is no error, but I'can't translate the datagrid

**Comment by jbty** [comment]
I also try this and it's not work

```javascript 
import { createTheme, Theme } from '@material-ui/core/styles'
import * as locales from '@material-ui/core/locale'
import * as dataGridLocales from '@material-ui/data-grid'

const LANGUAGES_MAPPING = {
  fr: 'frFR',
  en: 'enUS',
  es: 'esES',
  de: 'deDE',
}

export const MUI_LIGHT_THEME = (i18nLocalCode: string): Theme =>
  createTheme(
    {
      palette: {
        mode: 'light',
        primary: {
          main: '#ef7323',
        },
        secondary: {
          main: '#ef7323',
        },
        background: {
          default: '#f1f1f1',
          paper: '#ffffff',
        },
      },
      ...MUI_SHARED_STYLES,
    },
    // @ts-ignore
    locales[LANGUAGES_MAPPING[i18nLocalCode]],
    // @ts-ignore
    dataGridLocales[LANGUAGES_MAPPING[i18nLocalCode]]
  )

export const MUI_DARK_THEME = (i18nLocalCode: string): Theme =>
  createTheme(
    {
      palette: {
        mode: 'dark',
        primary: {
          main: '#ef7323',
        },
        secondary: {
          main: '#ef7323',
        },
        background: {
          default: '#181818',
          paper: '#131313',
        },
      },
      ...MUI_SHARED_STYLES,
    },
    // @ts-ignore
    locales[LANGUAGES_MAPPING[i18nLocalCode]],
    // @ts-ignore
    dataGridLocales[LANGUAGES_MAPPING[i18nLocalCode]]
  )
```
if we folow this doc :
[https://material-ui.com/components/data-grid/localization/](https://material-ui.com/components/data-grid/localization/)

and especialy this :
```javascript 
import { DataGrid, nlNL } from '@material-ui/data-grid';

<DataGrid localeText={nlNL.props.MuiDataGrid.localeText} />;
```

I notice 'props' does not exist in 'nlNL' in my case..

**Comment by m4theushw** [comment]
> if we follow this doc : https://material-ui.com/components/data-grid/localization/

How are you initializing your theme? If you follow https://material-ui.com/components/data-grid/localization/#locale-text it should work. 

> I notice 'props' does not exist in 'nlNL' in my case.. The doc is not up to date ?

The docs is for @material-ui/core v4. For v5 the correct path is `nlNL.components.MuiDataGrid.defaultProps.localeText`.

---

The warning about `defaultProps` is being emitted because we're not spreading the correct props when importing translations from the core. Here's a reproduction: https://codesandbox.io/s/material-demo-forked-xeimg?file=/demo.js This only occurs in v5. The following diff should fix it.

```diff
diff --git a/packages/grid/_modules_/grid/utils/getGridLocalization.ts b/packages/grid/_modules_/grid/utils/getGridLocalization.ts
index 370cd8a7..24644ea8 100644
--- a/packages/grid/_modules_/grid/utils/getGridLocalization.ts
+++ b/packages/grid/_modules_/grid/utils/getGridLocalization.ts
@@ -29,7 +29,7 @@ export const getGridLocalization = (
           defaultProps: {
             localeText: {
               ...gridTranslations,
-              MuiTablePagination: coreTranslations?.components?.MuiTablePagination,
+              MuiTablePagination: coreTranslations?.components?.MuiTablePagination.defaultProps,
             },
           },
         },
```

**Comment by jbty** [comment]
HI @m4theushw ,

Today I re write the theme init of my app, but I can get it to work :( 

here my component : 
```javascript
import React, { useEffect } from 'react'
import { createTheme, ThemeProvider } from '@material-ui/core/styles'
import * as coreLocales from '@material-ui/core/locale'
import * as gridLocale from '@material-ui/data-grid'
import { useTranslation } from 'react-i18next'
import { getLSVal } from '../libs/localStorage'
import { ColorMode, CompactMode } from '../typings/typings'
import {
  selectGlobalState,
  setThemeMode,
} from '../app/global-state/globalStateSlice'
import { useAppDispatch, useAppSelector } from '../app/hooks'
import { LANGUAGES_MAPPING } from '../constants/infos'
import { DARK_COLORS, LIGHT_COLORS, MAIN_THEME } from '../constants/styles'

export type SupportedLocales = keyof typeof coreLocales

const MaterialUiThemeProvider: React.FC = ({ children }) => {
  const dispatch = useAppDispatch()
  const { i18n } = useTranslation()
  const { colorMode } = useAppSelector(selectGlobalState)

  useEffect(() => {
    const savedDarkMode = getLSVal<ColorMode>('colorMode') || 'light'
    const savedCompactMode = getLSVal<CompactMode>('compactMode') || 'extended'

    dispatch(setThemeMode({ mode: 'colorMode', option: savedDarkMode }))
    dispatch(setThemeMode({ mode: 'compactMode', option: savedCompactMode }))
  }, [])

  const [currentLocale, setCurrentLocale] =
    React.useState<SupportedLocales>('frFR')

  useEffect(() => {
    const currentLanguage = i18n.languages[0] as 'fr' | 'en' | 'es' | 'de'

    setCurrentLocale(LANGUAGES_MAPPING[currentLanguage] as SupportedLocales)
  }, [i18n.languages])

  const theme = React.useMemo(
    () =>
      createTheme(
        {
          palette: colorMode === 'light' ? LIGHT_COLORS : DARK_COLORS,
          ...MAIN_THEME,
        },
        coreLocales[currentLocale],
        // @ts-ignore
        gridLocale[currentLocale]
      ),
    [colorMode, currentLocale]
  )

  return <ThemeProvider theme={theme}>{children}</ThemeProvider>
}

export default MaterialUiThemeProvider
```

I always get the error : 
````
index.js:1 Warning: React does not recognize the `defaultProps` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `defaultprops` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

**Comment by m4theushw** [comment]
So you can translate your app, but there's the `defaultProps` warning? Is that your concern? This warning is in our side, we have to fix it.

The translation in the reproduction is working. If you copy the same code to your project it should work.

**Comment by jbty** [comment]
No the translation does not work either, and if I change the language several times the table crashes with this error

```javascript
Error: Missing translation for key MuiTablePagination.
```
console.log :
```javascript
{
    "MuiDataGrid": {
        "defaultProps": {
            "localeText": {
                "MuiTablePagination": undefined <================== this output errors : Error: Missing translation for key MuiTablePagination.
                "noRowsLabel": "No rows",
                "noResultsOverlayLabel": "No results found.",
                "errorOverlayDefaultLabel": "An error occurred.",
                "toolbarDensity": "Density",
                "toolbarDensityLabel": "Density",
                "toolbarDensityCompact": "Compact",
                "toolbarDensityStandard": "Standard",
                "toolbarDensityComfortable": "Comfortable",
                "toolbarColumns": "Columns",
                "toolbarColumnsLabel": "Select columns",
                "toolbarFilters": "Filters",
                "toolbarFiltersLabel": "Show filters",
                "toolbarFiltersTooltipHide": "Hide filters",
                "toolbarFiltersTooltipShow": "Show filters",
                "toolbarExport": "Export",
                "toolbarExportLabel": "Export",
                "toolbarExportCSV": "Download as CSV",
                "columnsPanelTextFieldLabel": "Find column",
                "columnsPanelTextFieldPlaceholder": "Column title",
                "columnsPanelDragIconLabel": "Reorder column",
                "columnsPanelShowAllButton": "Show all",
                "columnsPanelHideAllButton": "Hide all",
                "filterPanelAddFilter": "Add filter",
                "filterPanelDeleteIconLabel": "Delete",
                "filterPanelOperators": "Operators",
                "filterPanelOperatorAnd": "And",
                "filterPanelOperatorOr": "Or",
                "filterPanelColumns": "Columns",
                "filterPanelInputLabel": "Value",
                "filterPanelInputPlaceholder": "Filter value",
                "filterOperatorContains": "contains",
                "filterOperatorEquals": "equals",
                "filterOperatorStartsWith": "starts with",
                "filterOperatorEndsWith": "ends with",
                "filterOperatorIs": "is",
                "filterOperatorNot": "is not",
                "filterOperatorAfter": "is after",
                "filterOperatorOnOrAfter": "is on or after",
                "filterOperatorBefore": "is before",
                "filterOperatorOnOrBefore": "is on or before",
                "filterValueAny": "any",
                "filterValueTrue": "true",
                "filterValueFalse": "false",
                "columnMenuLabel": "Menu",
                "columnMenuShowColumns": "Show columns",
                "columnMenuFilter": "Filter",
                "columnMenuHideColumn": "Hide",
                "columnMenuUnsort": "Unsort",
                "columnMenuSortAsc": "Sort by ASC",
                "columnMenuSortDesc": "Sort by DESC",
                "columnHeaderFiltersLabel": "Show filters",
                "columnHeaderSortIconLabel": "Sort",
                "footerTotalRows": "Total Rows:",
                "checkboxSelectionHeaderName": "Checkbox selection",
                "booleanCellTrueLabel": "true",
                "booleanCellFalseLabel": "false"
            }
        }
    }
}

```

**Comment by jbty** [comment]
I don't know why, but if I try this :
```javascript
createTheme(
        {
          palette: colorMode === 'light' ? LIGHT_COLORS : DARK_COLORS,
          ...MAIN_THEME,
        },
        {
          components: {
            ...coreLocales[currentLocale].components,
            // @ts-ignore
            ...gridLocale[currentLocale].components,
          },
        }
      ),
```

Translations work until I come across the error I told you about. If it can help I can temporarily share my github repository if you send me your github username by email

**Comment by m4theushw** [comment]
Could you fork this [CodeSandbox](https://codesandbox.io/s/material-demo-forked-xeimg?file=/demo.js) and update it with the code that is failing? It would help a lot to debug the cause.

**Comment by jbty** [comment]
@m4theushw thanks for you help ! 
it's late in France ^^, tomorrow I'll make you a sandbox code, I hope that will help

**Comment by jbty** [comment]
Hi,

I bought the x-grid material but the translation problem is also above :(. I created a sand box code with the error. I will also create a solution for another problem that I found.

[https://codesandbox.io/s/fervent-water-v83mh](https://codesandbox.io/s/fervent-water-v83mh)

**Comment by oliviertassinari** [comment]
@jbty Please provide a minimal reproduction. The GitHub bug tracker is meant for bugs on the data grid, we can't debug applications.

**Comment by m4theushw** [comment]
It's very easy to reproduce it. We just have to initialize the theme with the English locale and 💥. It breaks both with MUI v4 and v5. Here's a CodeSandbox: https://codesandbox.io/s/material-demo-forked-iml3y?file=/demo.js

It happens because the translations for this locale are commented in the core: https://github.com/mui-org/material-ui/blob/93aab64df3786a76eb2cc49c7848297ce6c63024/packages/material-ui/src/locale/index.ts#L620-L626
