### ISSUE TITLE
MUI: GridErrorHandler - An unexpected error occurred. Error: "t" is read-only.

### ISSUE THREAD

**Issue by MajdiVmk** [mui-org/material-ui-x#3553]
### Order ID 💳

11111

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

This is my code and i don't know why give me the same error 
**An error occurred.**

with console error 
**### MUI: GridErrorHandler - An unexpected error occurred. Error: "t" is read-only.**

```
import React from 'react';
import {
    DataGridPro,
    GridRowsProp,
    GridColDef,
    LicenseInfo,
} from '@mui/x-data-grid-pro';

const rows: GridRowsProp = [
    { id: 1, col1: 'Hello', col2: 'World' },
    { id: 2, col1: 'XGrid', col2: 'is Awesome' },
    { id: 3, col1: 'Material-UI', col2: 'is Amazing' },
    { id: 4, col1: 'Hello', col2: 'World' },
    { id: 5, col1: 'XGrid', col2: 'is Awesome' },
    { id: 6, col1: 'Material-UI', col2: 'is Amazing' },
];

const columns: GridColDef[] = [
    { field: 'id', hide: true },
    { field: 'col1', headerName: 'Column 1', width: 150 },
    { field: 'col2', headerName: 'Column 2', width: 150 },
];

const App = () => {
    LicenseInfo.setLicenseKey(
        '######',
    );
    return (
        <div style={{ height: 300, width: '100%' }}>
            <DataGridPro
                rows={rows}
                columns={columns}
            />
        </div>
    );
};

export default App;

```

### Your environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @material-ui/envinfo` goes here.
```
</details>

**Comment by m4theushw** [comment]
Could you paste the entire error message, including the line/column number? It could be related to https://github.com/mui-org/material-ui-x/issues/2333.

A live example could also be added. [This **codesandbox.io** template](https://codesandbox.io/s/datagrid-v5-quick-start-54iz1) _may_ be a good starting point. If you can't reproduce it in CodeSandbox, a GitHub repository can also be used.

**Comment by iocuydi** [comment]
Experiencing the same thing, however it only occurs for me when I deploy to production on a service like AWS Amplify or Netlify. When testing locally it does not occur. I also have a separate project using the same version of MUI DataGrid that is deployed to production and not affected. I believe it is due to some interaction with other installed libraries. Also, I believe it may similar to this issue on a different project: https://github.com/facebookexperimental/Recoil/issues/122

**Comment by MajdiVmk** [comment]
I've tried it before and still not working
and I have a **License Key**
[live example](https://codesandbox.io/s/datagrid-v5-quick-start-54iz1)

I think the error occur cause the packages
I have these packages:

> "@material-ui/core": "^4.11.3",
>         "@material-ui/data-grid": "^4.0.0-alpha.37",
>         "@material-ui/icons": "^4.11.2",
>         "@material-ui/lab": "^4.0.0-alpha.57",
>         "@material-ui/pickers": "^3.2.10",
>         "@material-ui/styles": "^4.11.3",
>         "@mui/icons-material": "^5.2.1",
>         "@mui/lab": "^5.0.0-alpha.55",
>         "@mui/material": "^5.0.2",
>         "@mui/styled-engine-sc": "^5.1.0",
>         "@mui/styles": "^5.1.1",
>         "@mui/x-data-grid": "^5.2.0",
>         "@mui/x-data-grid-generator": "^5.2.1",
>         "@mui/x-data-grid-pro": "^5.2.1",
>         "@mui/x-license-pro": "latest",

**### I have used both versions, but I need it.**

_Error: 1_
**index.js:1 The above error occurred in the <ForwardRef> component:**

    at http://localhost:3000/static/js/12.chunk.js:23470:11
    at div
    at http://localhost:3000/static/js/12.chunk.js:14229:13
    at div
    at http://localhost:3000/static/js/1.chunk.js:1700:73
    at Me (http://localhost:3000/static/js/12.chunk.js:14091:14)
    at Pt (http://localhost:3000/static/js/12.chunk.js:14494:13)
    at Mt (http://localhost:3000/static/js/12.chunk.js:14566:189)
    at Lt (http://localhost:3000/static/js/12.chunk.js:14604:13)
    at div
    at http://localhost:3000/static/js/1.chunk.js:1700:73
    at NoSsr (http://localhost:3000/static/js/1.chunk.js:13937:24)
    at http://localhost:3000/static/js/12.chunk.js:17198:11
    at rs (http://localhost:3000/static/js/12.chunk.js:21263:18)
    at http://localhost:3000/static/js/12.chunk.js:25644:16
    at div
    at FilterOperators (http://localhost:3000/static/js/14.chunk.js:332:100)
    at div
    at Container (http://localhost:3000/static/js/11.chunk.js:7857:23)
    at WithStyles (http://localhost:3000/static/js/11.chunk.js:185155:31)
    at div
    at http://localhost:3000/static/js/2.chunk.js:458:23
    at PatientListView (http://localhost:3000/static/js/14.chunk.js:1843:17)
    at Route (http://localhost:3000/static/js/11.chunk.js:354919:29)
    at Switch (http://localhost:3000/static/js/11.chunk.js:355121:29)
    at Suspense
    at div
    at div
    at div
    at div
    at DashboardLayout (http://localhost:3000/static/js/main.chunk.js:4848:23)
    at Route (http://localhost:3000/static/js/11.chunk.js:354919:29)
    at Switch (http://localhost:3000/static/js/11.chunk.js:355121:29)
    at Suspense
    at AuthProvider (http://localhost:3000/static/js/main.chunk.js:1835:24)
    at Router (http://localhost:3000/static/js/11.chunk.js:354550:30)
    at BrowserRouter (http://localhost:3000/static/js/11.chunk.js:352877:35)
    at SnackbarProvider (http://localhost:3000/static/js/11.chunk.js:275995:24)
    at MuiPickersUtilsProvider (http://localhost:3000/static/js/11.chunk.js:183322:20)
    at StylesProvider (http://localhost:3000/static/js/11.chunk.js:183670:24)
    at ThemeProvider (http://localhost:3000/static/js/11.chunk.js:183857:24)
    at App (http://localhost:3000/static/js/main.chunk.js:215:92)
    at SettingsProvider (http://localhost:3000/static/js/main.chunk.js:2260:23)
    at Provider (http://localhost:3000/static/js/11.chunk.js:350277:20)

React will try to recreate this component tree from scratch using the error boundary you provided, Mt.

_Error: 2_ 
**index.js:1 MUI: GridErrorHandler - An unexpected error occurred. Error: "t" is read-only.  Error: "t" is read-only**
    at _readOnlyError (readOnlyError.js:2)
    at getRows (index-esm.js:15)
    at index-esm.js:15
    at renderWithHooks (react-dom.development.js:14985)
    at updateForwardRef (react-dom.development.js:17044)
    at beginWork (react-dom.development.js:19098)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
    at invokeGuardedCallback (react-dom.development.js:4056)
    at beginWork$1 (react-dom.development.js:23964)
    at performUnitOfWork (react-dom.development.js:22776)
    at workLoopSync (react-dom.development.js:22707)
    at renderRootSync (react-dom.development.js:22670)
    at performSyncWorkOnRoot (react-dom.development.js:22293)
    at react-dom.development.js:11327
    at unstable_runWithPriority (scheduler.development.js:646)
    at runWithPriority$1 (react-dom.development.js:11276)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11322)
    at flushSyncCallbackQueue (react-dom.development.js:11309)
    at scheduleUpdateOnFiber (react-dom.development.js:21893)
    at dispatchAction (react-dom.development.js:16139)
    at _callee2$ (index.js:1)
    at tryCatch (runtime.js:63)
    at Generator.invoke [as _invoke] (runtime.js:293)
    at Generator.next (runtime.js:118)
    at i (_tslib-832fff42.js:15) undefined

**Comment by MajdiVmk** [comment]
> Experiencing the same thing, however it only occurs for me when I deploy to production on a service like AWS Amplify or Netlify. When testing locally it does not occur. I also have a separate project using the same version of MUI DataGrid that is deployed to production and not affected. I believe it is due to some interaction with other installed libraries. Also, I believe it may be similar to this issue on a different project: [facebookexperimental/Recoil#122](https://github.com/facebookexperimental/Recoil/issues/122)

**I guess this too.**

**Comment by scuilla** [comment]
Experiencing this same problem, but on local. Stacktrace is identical.

**Environment:**

System:
    OS: Windows 10 10.0.19042
  Binaries:
    Node: 14.15.4 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.10 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (96.0.1054.62)
  npmPackages:
    @emotion/react: ^11.7.1 => 11.7.1
    @emotion/styled: ^11.6.0 => 11.6.0
    @mui/base:  5.0.0-alpha.63
    @mui/icons-material: ^5.2.5 => 5.2.5
    @mui/lab: ^5.0.0-alpha.63 => 5.0.0-alpha.63
    @mui/material: ^5.2.7 => 5.2.7
    @mui/private-theming:  5.2.3
    @mui/styled-engine:  5.2.6
    @mui/styles: ^5.2.3 => 5.2.3
    @mui/system:  5.2.6
    @mui/types:  7.1.0
    @mui/utils:  5.2.3
    @mui/x-data-grid: ^5.2.1 => 5.2.2
    @mui/x-data-grid-pro: ^5.2.1 => 5.2.2
    @mui/x-license-pro: ^5.2.2 => 5.2.2
    @types/react:  16.9.43
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    typescript: ^4.5.4 => 4.5.4

**Comment by edouardruiz** [comment]
Same issue here with a project base on CRA (`"react-scripts": "4.0.3"`) only with a production build (served in local or hosted on AWS). On both Chrome and Safari.

The output of the `npx @material-ui/envinfo` command:

```
  System:
    OS: macOS 12.1
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.15 - ~/Documents/Projects/next/next-frontend/node_modules/.bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Chrome: 96.0.4664.110
    Edge: Not Found
    Firefox: 95.0.2
    Safari: 15.2
  npmPackages:
    @emotion/react: ^11.7.1 => 11.7.1 
    @emotion/styled: ^11.6.0 => 11.6.0 
    @types/react:  16.9.56 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    typescript:  4.5.4 
```

And the below MUI packages installed:

```
    "@emotion/react": "^11.7.1",
    "@emotion/styled": "^11.6.0",
    "@mui/icons-material": "^5.2.5",
    "@mui/lab": "5.0.0-alpha.63",
    "@mui/material": "^5.2.7",
    "@mui/system": "^5.2.6",
    "@mui/x-data-grid-pro": "^5.2.2",
```

And the same stacktrace:

```
MUI: GridErrorHandler - An unexpected error occurred. Error: "t" is read-only.  Error: "t" is read-only
    at r (readOnlyError.js:2)
    at getRows (index-esm.js:15)
    at index-esm.js:15
    at oi (react-dom.production.min.js:157)
    at Ii (react-dom.production.min.js:176)
    at qu (react-dom.production.min.js:271)
    at Sc (react-dom.production.min.js:250)
    at Dc (react-dom.production.min.js:250)
    at Cc (react-dom.production.min.js:250)
    at vc (react-dom.production.min.js:243)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:18)
    at Uo (react-dom.production.min.js:122)
    at Go (react-dom.production.min.js:123)
    at $o (react-dom.production.min.js:122)
    at Mc (react-dom.production.min.js:263)
    at t.unstable_runWithPriority (scheduler.production.min.js:18)
    at Uo (react-dom.production.min.js:122)
    at Ac (react-dom.production.min.js:261)
    at react-dom.production.min.js:261
    at L (scheduler.production.min.js:16)
    at MessagePort.j.port1.onmessage (scheduler.production.min.js:12) undefined
```

**Comment by edouardruiz** [comment]
The issue was fixed for us by deleting the `node_modules` folder and the `package-lock.json` and running `npm install`.

**Comment by MajdiVmk** [comment]
> The issue was fixed for us by deleting the `node_modules` folder and the `package-lock.json` and running `npm install`.

I think there is another solution without remove lock file.

**Comment by m4theushw** [comment]
@MajdiVmk The live example you sent uses dependencies in their `latest` version, so we don't know exactly which version was installed. Could you create a GitHub repository or paste the `yarn.lock`?

**Comment by MajdiVmk** [comment]
> @MajdiVmk The live example you sent uses dependencies in their `latest` version, so we don't know exactly which version was installed. Could you create a GitHub repository or paste the `yarn.lock`?

Of course,
yarn.lock

[yarnlock.txt](https://github.com/mui-org/material-ui-x/files/7844936/yarnlock.txt)

**Comment by m4theushw** [comment]
I downloaded the .zip from https://github.com/mui-org/material-ui-x/issues/3553#issuecomment-1006389598, then placed the `yarn.lock` provided, ran `yarn build` and started a local server and nothing. I couldn't see the error. I would appreciate if you could give more instructions on how to reproduce it. Notice that https://mui.com/components/data-grid/ is deployed on Netlify, so we should also experiment this problem if https://github.com/mui-org/material-ui-x/issues/3553#issuecomment-1006180440 is correct.

**Comment by LiberationNetwork** [comment]
Hmm I am facing the same issue ..

**Comment by dgoemans** [comment]
Same issue, only on the AWS Cloudfront CDN, not local.
envinfo:

```
  System:
    OS: Windows 10 10.0.22000
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 99.0.4844.82
    Edge: Spartan (44.22000.120.0), Chromium (99.0.1150.55)
  npmPackages:
    @material-ui/core: 4.12.3 => 4.12.3
    @material-ui/data-grid: ^4.0.0-alpha.37 => 4.0.0-alpha.37
    @material-ui/icons: 4.11.2 => 4.11.2
    @material-ui/lab: ^4.0.0-alpha.60 => 4.0.0-alpha.60
    @material-ui/pickers: 3.3.10 => 3.3.10
    @material-ui/styles:  4.11.4
    @material-ui/system:  4.12.1
    @material-ui/types:  5.1.0
    @material-ui/utils:  4.11.2
    @types/react: 16.9.0 => 16.9.0
    react: 16.14.0 => 16.14.0
    react-dom: 16.14.0 => 16.14.0
    styled-components: 4.4.1 => 4.4.1
    typescript: 3.9.4 => 3.9.4
```

After yarn upgrade:

```
  System:
    OS: Windows 10 10.0.22000
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 99.0.4844.82
    Edge: Spartan (44.22000.120.0), Chromium (99.0.1150.55)
  npmPackages:
    @material-ui/core: 4.12.3 => 4.12.3
    @material-ui/data-grid: ^4.0.0-alpha.37 => 4.0.0-alpha.37
    @material-ui/icons: 4.11.2 => 4.11.2
    @material-ui/lab: ^4.0.0-alpha.60 => 4.0.0-alpha.60
    @material-ui/pickers: 3.3.10 => 3.3.10
    @material-ui/styles:  4.11.4
    @material-ui/system:  4.12.1
    @material-ui/types:  5.1.0
    @material-ui/utils:  4.11.2
    @types/react: 16.9.0 => 16.9.0
    react: 16.14.0 => 16.14.0
    react-dom: 16.14.0 => 16.14.0
    styled-components: 4.4.1 => 4.4.1
    typescript: 3.9.4 => 3.9.4
```

After running a yarn upgrade, I noticed some warnings being logged about my setting DataGrid's `pageSize` to a value of 15 was not valid in the config. Changing this to `autoPageSize` made that warning go away. Not sure what fixed it in the end, since my `yarn upgrade` had several small things that needed fixing before i could deploy (because ESLint + plugins also got updated), but after this it's all good again.
